apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: SelfService-PortalUI-TemplateManagement
  name: SelfService-PortalUI-TemplateManagement
spec:
  output:
    to:
      kind: DockerImage
      name: SelfService-PortalUI-TemplateManagement:latest
  source:
    type: Git
    git:
      uri: 'https://github.com/Anildth/nodejs-app-mss.git'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
