apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: node-js
  name: node-js
spec:
  output:
    to:
      kind: DockerImage
      name: node-js:latest
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
